In [1]:
import pandas as pd
import numpy as np

In [2]:
#R library(randomForest)
from sklearn.ensemble import RandomForestClassifier

In [3]:
#R df = read.csv(file="./data/proposed-assessments-as-of-april-18th.csv", header=TRUE, sep=",")
df = pd.read_csv("data/proposed-assessments-as-of-april-18th.csv",low_memory=False)

In [4]:
# orig = read.csv(file="./data/proposed-assessments-as-of-april-18th.csv", header=TRUE, sep=",")
# OMITTED IN PORT

In [5]:
#R df = df[sapply(df, is.numeric)]
# this should select only the numeric columns
df = df.select_dtypes(exclude=['object'])
df.head(5)

,BlockNo,SalePrice,2017 Assmt Taxable,2017 Assmt Exempt,2017 Assmt Total,2017 Taxes Total,Year Built,Square Footage,2018 Assmt Taxable,2018 Assmt Exempt,2018 Assmt Total,2018 Taxes Estimated
0,301.0,390000.0,126000,NaN,126000,9828.0,1925.0,1600.0,416500,NaN,416500,6747.30
1,301.0,1.0,114000,NaN,114000,8892.0,1929.0,1616.0,363300,NaN,363300,5885.46
2,301.0,150000.0,124700,NaN,124700,9726.6,1929.0,1600.0,364900,NaN,364900,5911.38
3,301.0,305000.0,88000,NaN,88000,6864.0,1929.0,1582.0,335000,NaN,335000,5427.00
4,301.0,1.0,122100,NaN,122100,9523.8,1929.0,1582.0,396200,NaN,396200,6418.44

In [6]:
list(df)

['BlockNo',
 'SalePrice',
 '2017 Assmt\nTaxable',
 '2017 Assmt\nExempt',
 '2017 Assmt\nTotal',
 '2017 Taxes\nTotal',
 'Year\nBuilt',
 'Square\nFootage',
 '2018 Assmt\nTaxable',
 '2018 Assmt\nExempt',
 '2018 Assmt\nTotal',
 '2018 Taxes\nEstimated']

In [7]:
#R undesired <- c('X2018.Assmt.Taxable', 'X2018.Assmt.Exempt', 'X2018.Assmt.Total')
undesired = ['2018 Assmt\nTaxable', '2018 Assmt\nExempt', '2018 Assmt\nTotal']

In [10]:
#R idx = !(colnames(df) %in% undesired)
idx = [x for x in list(df) if x not in undesired]
idx

['BlockNo',
 'SalePrice',
 '2017 Assmt\nTaxable',
 '2017 Assmt\nExempt',
 '2017 Assmt\nTotal',
 '2017 Taxes\nTotal',
 'Year\nBuilt',
 'Square\nFootage',
 '2018 Taxes\nEstimated']

In [11]:
#R df = df[,idx]
# creates an index on all the columns except those in undesired
df.set_index(idx)

                                                                                                                                                2018 Assmt\nTaxable  \
BlockNo SalePrice 2017 Assmt\nTaxable 2017 Assmt\nExempt 2017 Assmt\nTotal 2017 Taxes\nTotal Year\nBuilt Square\nFootage 2018 Taxes\nEstimated
301.0   390000.0  126000              NaN                126000            9828.0            1925.0      1600.0          6747.30                             416500
        1.0       114000              NaN                114000            8892.0            1929.0      1616.0          5885.46                             363300
        150000.0  124700              NaN                124700            9726.6            1929.0      1600.0          5911.38                             364900
        305000.0  88000               NaN                88000             6864.0            1929.0      1582.0          5427.00                             335000
        1.0       122100              NaN                122100            9523.8            1929.0      1582.0          6418.44                             396200
        120000.0  90000               NaN                90000             7020.0            1929.0      1600.0          6318.00                             390000
        1.0       124400              NaN                124400            9703.2            1929.0      1582.0          6533.46                             403300
        282000.0  95000               NaN                95000             7410.0            1929.0      1582.0          6612.84                             408200
        1.0       112700              NaN                112700            8790.6            1929.0      1622.0          6988.68                             431400
        93500.0   93500               NaN                93500             7293.0            1929.0      1480.0          5587.38                             344900
        175000.0  70000               NaN                70000             5460.0            1929.0      1582.0          5763.96                             355800
        1.0       122300              NaN                122300            9539.4            1929.0      1600.0          6774.84                             418200
        37750.0   101000              NaN                101000            7878.0            1929.0      1680.0          6885.00                             425000
        330000.0  80000               NaN                80000             6240.0            1929.0      1680.0          6199.74                             382700
        360000.0  100000              NaN                100000            7800.0            1929.0      1694.0          6099.30                             376500
        285000.0  86000               NaN                86000             6708.0            1929.0      1771.0          6593.40                             407000
        376000.0  117400              NaN                117400            9157.2            1929.0      1736.0          6029.64                             372200
        167000.0  100000              NaN                100000            7800.0            1929.0      1736.0          5914.62                             365100
        1.0       127500              NaN                127500            9945.0            1929.0      1814.0          6645.24                             410200
        184000.0  124800              NaN                124800            9734.4            1929.0      2079.0          6637.14                             409700
        1.0       130000              NaN                130000            10140.0           1975.0      3780.0          9305.28                             574400
302.0   465000.0  116500              NaN                116500            9087.0            2000.0      2363.0          9788.04                             604200
        345400.0  127000              NaN                127000            9906.0            1929.0      1638.0          6862.32                             423600
        355000.0  127000              NaN                127000            9906.0            1929.0      1638.0          6799.14                             419700
        405000.0  127000              NaN                127000            9906.0            1929.0      1638.0          6792.66                             419300
        1.0       84500               NaN                84500             6591.0            1929.0      1638.0          6842.88                             422400
        216000.0  127000              NaN                127000            9906.0            1929.0      1764.0          6599.88                             407400
        390000.0  125000              NaN                125000            9750.0            1929.0      1596.0          6237.00                             385000
        321000.0  114000              NaN                114000            8892.0            1929.0      1638.0          7165.26                             442300
        1.0       125000              NaN                125000            9750.0            1929.0      1638.0          6951.42                             429100
...                                                                                                                                                             ...
30106.0 95000.0   68500               NaN                68500             5343.0            1925.0      1816.0          4821.12                             297600
        1.0       70900               NaN                70900             5530.2            1925.0      1682.0          4437.18                             273900
        145000.0  87600               NaN                87600             6832.8            1925.0      1797.0          4288.14                             264700
        182500.0  80200               NaN                80200             6255.6            1925.0      2016.0          4905.36                             302800
        1.0       90100               NaN                90100             7027.8            1925.0      1727.0          4842.18                             298900
        125000.0  71700               NaN                71700             5592.6            1900.0      1180.0          3063.42                             189100
        590000.0  130000              NaN                130000            10140.0           2006.0      3693.0          9157.86                             565300
        85000.0   71900               NaN                71900             5608.2            1900.0      1180.0          1987.74                             122700
        40000.0   80100               NaN                80100             6247.8            1925.0      1512.0          4458.24                             275200
        150000.0  89700               NaN                89700             6996.6            1925.0      1906.0          4983.12                             307600
        117000.0  80100               NaN                80100             6247.8            1925.0      1330.0          3865.32                             238600
        275000.0  80200               NaN                80200             6255.6            1900.0      1397.0          4443.66                             274300
        466000.0  100000              NaN                100000            7800.0            1925.0      3036.0          8048.16                             496800
        529999.0  164700              NaN                164700            12846.6           1925.0      3036.0          8503.38                             524900
        330000.0  100000              NaN                100000            7800.0            1920.0      2624.0          5060.88                             312400
        0.0       99100               NaN                99100             7729.8            1916.0      2674.0          5104.62                             315100
        235000.0  85900               NaN                85900             6700.2            1925.0      2904.0          6763.50                             417500
        10.0      77400               NaN                77400             6037.2            1925.0      2904.0          6371.46                             393300
30304.0 130000.0  89000               NaN                89000             6942.0            1925.0      2000.0          4725.54                             291700
        167000.0  76000               NaN                76000             5928.0            1900.0      2000.0          4469.58                             275900
        282000.0  75000               NaN                75000             5850.0            1925.0      2020.0          4489.02                             277100
        40000.0   75000               NaN                75000             5850.0            1925.0      2020.0          4500.36                             277800
        1.0       75000               NaN                75000             5850.0            1925.0      2000.0          4519.80                             279000
        0.0       78000               NaN                78000             6084.0            1925.0      1978.0          4493.88                             277400
        205000.0  60800               NaN                60800             4742.4            1968.0      1860.0          4498.74                             277700
        40000.0   60800               NaN                60800             4742.4            1925.0      1860.0          3819.96                             235800
        1.0       75000               NaN                75000             5850.0            1925.0      1882.0          4390.20                             271000
        40000.0   60800               NaN                60800             4742.4            1925.0      1882.0          4403.16                             271800
        1.0       75000               NaN                75000             5850.0            1969.0      1860.0          4344.84                             268200
                  78000               NaN                78000             6084.0            1925.0      1860.0          4354.56                             268800

                                                                                                                                                2018 Assmt\nExempt  \
BlockNo SalePrice 2017 Assmt\nTaxable 2017 Assmt\nExempt 2017 Assmt\nTotal 2017 Taxes\nTotal Year\nBuilt Square\nFootage 2018 Taxes\nEstimated
301.0   390000.0  126000              NaN                126000            9828.0            1925.0      1600.0          6747.30                               NaN
        1.0       114000              NaN                114000            8892.0            1929.0      1616.0          5885.46                               NaN
        150000.0  124700              NaN                124700            9726.6            1929.0      1600.0          5911.38                               NaN
        305000.0  88000               NaN                88000             6864.0            1929.0      1582.0          5427.00                               NaN
        1.0       122100              NaN                122100            9523.8            1929.0      1582.0          6418.44                               NaN
        120000.0  90000               NaN                90000             7020.0            1929.0      1600.0          6318.00                               NaN
        1.0       124400              NaN                124400            9703.2            1929.0      1582.0          6533.46                               NaN
        282000.0  95000               NaN                95000             7410.0            1929.0      1582.0          6612.84                               NaN
        1.0       112700              NaN                112700            8790.6            1929.0      1622.0          6988.68                               NaN
        93500.0   93500               NaN                93500             7293.0            1929.0      1480.0          5587.38                               NaN
        175000.0  70000               NaN                70000             5460.0            1929.0      1582.0          5763.96                               NaN
        1.0       122300              NaN                122300            9539.4            1929.0      1600.0          6774.84                               NaN
        37750.0   101000              NaN                101000            7878.0            1929.0      1680.0          6885.00                               NaN
        330000.0  80000               NaN                80000             6240.0            1929.0      1680.0          6199.74                               NaN
        360000.0  100000              NaN                100000            7800.0            1929.0      1694.0          6099.30                               NaN
        285000.0  86000               NaN                86000             6708.0            1929.0      1771.0          6593.40                               NaN
        376000.0  117400              NaN                117400            9157.2            1929.0      1736.0          6029.64                               NaN
        167000.0  100000              NaN                100000            7800.0            1929.0      1736.0          5914.62                               NaN
        1.0       127500              NaN                127500            9945.0            1929.0      1814.0          6645.24                               NaN
        184000.0  124800              NaN                124800            9734.4            1929.0      2079.0          6637.14                               NaN
        1.0       130000              NaN                130000            10140.0           1975.0      3780.0          9305.28                               NaN
302.0   465000.0  116500              NaN                116500            9087.0            2000.0      2363.0          9788.04                               NaN
        345400.0  127000              NaN                127000            9906.0            1929.0      1638.0          6862.32                               NaN
        355000.0  127000              NaN                127000            9906.0            1929.0      1638.0          6799.14                               NaN
        405000.0  127000              NaN                127000            9906.0            1929.0      1638.0          6792.66                               NaN
        1.0       84500               NaN                84500             6591.0            1929.0      1638.0          6842.88                               NaN
        216000.0  127000              NaN                127000            9906.0            1929.0      1764.0          6599.88                               NaN
        390000.0  125000              NaN                125000            9750.0            1929.0      1596.0          6237.00                               NaN
        321000.0  114000              NaN                114000            8892.0            1929.0      1638.0          7165.26                               NaN
        1.0       125000              NaN                125000            9750.0            1929.0      1638.0          6951.42                               NaN
...                                                                                                                                                            ...
30106.0 95000.0   68500               NaN                68500             5343.0            1925.0      1816.0          4821.12                               NaN
        1.0       70900               NaN                70900             5530.2            1925.0      1682.0          4437.18                               NaN
        145000.0  87600               NaN                87600             6832.8            1925.0      1797.0          4288.14                               NaN
        182500.0  80200               NaN                80200             6255.6            1925.0      2016.0          4905.36                               NaN
        1.0       90100               NaN                90100             7027.8            1925.0      1727.0          4842.18                               NaN
        125000.0  71700               NaN                71700             5592.6            1900.0      1180.0          3063.42                               NaN
        590000.0  130000              NaN                130000            10140.0           2006.0      3693.0          9157.86                               NaN
        85000.0   71900               NaN                71900             5608.2            1900.0      1180.0          1987.74                               NaN
        40000.0   80100               NaN                80100             6247.8            1925.0      1512.0          4458.24                               NaN
        150000.0  89700               NaN                89700             6996.6            1925.0      1906.0          4983.12                               NaN
        117000.0  80100               NaN                80100             6247.8            1925.0      1330.0          3865.32                               NaN
        275000.0  80200               NaN                80200             6255.6            1900.0      1397.0          4443.66                               NaN
        466000.0  100000              NaN                100000            7800.0            1925.0      3036.0          8048.16                               NaN
        529999.0  164700              NaN                164700            12846.6           1925.0      3036.0          8503.38                               NaN
        330000.0  100000              NaN                100000            7800.0            1920.0      2624.0          5060.88                               NaN
        0.0       99100               NaN                99100             7729.8            1916.0      2674.0          5104.62                               NaN
        235000.0  85900               NaN                85900             6700.2            1925.0      2904.0          6763.50                               NaN
        10.0      77400               NaN                77400             6037.2            1925.0      2904.0          6371.46                               NaN
30304.0 130000.0  89000               NaN                89000             6942.0            1925.0      2000.0          4725.54                               NaN
        167000.0  76000               NaN                76000             5928.0            1900.0      2000.0          4469.58                               NaN
        282000.0  75000               NaN                75000             5850.0            1925.0      2020.0          4489.02                               NaN
        40000.0   75000               NaN                75000             5850.0            1925.0      2020.0          4500.36                               NaN
        1.0       75000               NaN                75000             5850.0            1925.0      2000.0          4519.80                               NaN
        0.0       78000               NaN                78000             6084.0            1925.0      1978.0          4493.88                               NaN
        205000.0  60800               NaN                60800             4742.4            1968.0      1860.0          4498.74                               NaN
        40000.0   60800               NaN                60800             4742.4            1925.0      1860.0          3819.96                               NaN

# ----- working to here

In [ ]:
#R for(i in 1:ncol(df)){
#R   df[is.na(df[,i]), i] = median(df[,i], na.rm = TRUE)
#R }

In [ ]:
#R rf = randomForest(X2018.Taxes.Estimated ~ ., data=df)
rf = RandomForestClassifier(n_estimators=5, random_state=2)
rf.fit(X2018.Taxes.Estimated ~ .,df)

#R diff = predict(rf, df) - df$X2018.Taxes.Estimated

In [ ]:
#R x = seq(0,5,0.1)
#R plot(seq(0,5,0.1), sapply(x, function(w) dim(df[abs(diff)>w*sd(diff),])[1]))